export type Color =
  | "red"
  | "orange"
  | "yellow"
  | "olive"
  | "green"
  | "teal"
  | "blue"
  | "violet"
  | "purple"
  | "pink"
  | "brown"
  | "grey"
  | "black"

export type SortBy = "favorite" | "font" | "calendar" | "setting" | ""
export type SortDirection = "sort content ascending" | "sort content descending"
